#include <stdio.h>
/**
 * main - Entry point of the program
 *
 * Description: This program finds and prints the sum of the even-valued terms
 * in the Fibonacci sequence whose values do not exceed 4,000,000. The Fibonacci
 * sequence is generated by adding the previous two terms, starting with 1 and 2.
 *
 * Return: Always 0 (success)
 */
int main() 
{
    int a = 1, b = 2, temp, sum_even = 0;

    while (b <= 4000000) 
    {
        if (b % 2 == 0) 
	{
            sum_even += b;
        }
        temp = a + b;
        a = b;
        b = temp;
    }

    printf("%d\n", sum_even);

    return (0);
}

